In [3]:
import pandas as pd
manual_labeling_anuja = pd.read_csv('crowdsource_anuja.csv')
manual_labeling_anuja['title'] = manual_labeling_anuja['title'].str.lower()

In [4]:
labeled = manual_labeling_anuja.copy()

In [16]:
# Define keywords for job levels
entry_keywords = [' 2', 'designer', 'administrator', ' i ','staff', 'dba', 'junior', 'assistant', 'entry', 'graduate', 'intern', 'trainee', 'aide','collector','technician' ]
mid_keywords = ['data scientist', 'steward', ' ii','mid', 'associate', 'specialist', 'coordinator', 'analyst', 'engineer', 'developer']
senior_keywords = ['vp ', 'architect', 'mentor', 'supervisor', 'sr. ','head ','sr ', 'president', ' iii','senior', 'lead', 'manager', 'director', 'principal', 'executive', 'chief']

# Function to label job levels based on the title and blurb
def label_job_level(row):
    title = str(row['title']).lower()
    blurb = str(row['blurb']).lower()
    #print(str(row['job_level']))
    
    # if job_level == 'Entry-Level' or job_level == 'Mid-Level' or job_level == 'Senior-Level':
    #     return str(row['job_level'])
    if any(keyword in title or keyword in blurb for keyword in senior_keywords):
        return 'Senior-Level'
    elif any(keyword in title or keyword in blurb for keyword in mid_keywords):
        return 'Mid-Level'
    elif any(keyword in title or keyword in blurb for keyword in entry_keywords):
        return 'Entry-Level'
    else:
        return 'Uncategorized'

# Apply the labeling function
labeled['job_level'] = labeled.apply(label_job_level, axis=1)

# Count job levels for an overview
job_level_counts = labeled['job_level'].value_counts()
job_level_counts

job_level
Uncategorized    153
Mid-Level        102
Senior-Level      46
Entry-Level       43
Name: count, dtype: int64

In [17]:
labeled.loc[labeled['id'] == 'IndeedScraperUSAEng_435912f3b9db5520', 'job_level'] = 'Mid-Level'

In [18]:
labeled

,status,title,company,location,date,blurb,tags,link,id,provider,query,locale,wage,remoteness,state_zip,state,city,job_level
0,NEW,credit strategy data scientist,Bill.com,"San Jose, CA",2024-10-03,Demonstrated history of addressing business ch...,"Benefits: Health savings account, Employee sto...",https://www.indeed.com/m/viewjob?jk=d88ba94179...,IndeedScraperUSAEng_d88ba941796f329e,IndeedScraperUSAEng,Data,USA_ENGLISH,$110200 - $132100 yearly,UNKNOWN,CA,CA,San Jose,Mid-Level
1,NEW,database administrator,Om Tek,"Irving, TX 75038",2024-10-05,9am to 6pm; Monday through Friday. JOB DUTIES ...,Job types: Full-time\r\nJob types cc: Full-tim...,https://www.indeed.com/m/viewjob?jk=f2e1c22eab...,IndeedScraperUSAEng_f2e1c22eab5c6a13,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,UNKNOWN,TX 75038,TX,Irving,Entry-Level
2,NEW,data scientist,Apple,"Cupertino, CA",2024-11-10,Deep expertise in data and model evaluation. S...,"Benefits: Employee stock purchase plan, Health...",https://www.indeed.com/m/viewjob?jk=b7898ec674...,IndeedScraperUSAEng_b7898ec674cc9781,IndeedScraperUSAEng,Data,USA_ENGLISH,$143100 - $264200 yearly,UNKNOWN,CA,CA,Cupertino,Mid-Level
3,NEW,"reporter, data, data journalism team",The New York Times,"New York, NY",2024-10-03,"As a data reporter, youâ€™ll combine traditional...",Job types: Full-time\r\nRemote: Hybrid work\r\...,https://www.indeed.com/m/viewjob?jk=435912f3b9...,IndeedScraperUSAEng_435912f3b9db5520,IndeedScraperUSAEng,Data,USA_ENGLISH,$111049.64 - $140000 yearly,TEMPORARILY_REMOTE,NY,NY,New York,Mid-Level
4,NEW,data solution architect,Corpay,"Dallas, TX",2024-11-05,You have experience in enterprise data modelin...,Job types: Full-time\r\nShifts: 8 hour shift\r...,https://www.indeed.com/m/viewjob?jk=750814a003...,IndeedScraperUSAEng_750814a0033da0e7,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,FULLY_REMOTE,TX,TX,Dallas,Senior-Level
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,NEW,machine learning research scientist,Output Biosciences,"New York, NY",2024-10-09,"You are comfortable working with large, divers...",Job types: Full-time\r\nBenefits: Health insur...,https://www.indeed.com/m/viewjob?jk=db18fca764...,IndeedScraperUSAEng_db18fca764b769d1,IndeedScraperUSAEng,Data,USA_ENGLISH,$120000 - $250000 yearly,UNKNOWN,NY,NY,New York,Uncategorized
340,NEW,competitive pricing architect,NTT DATA,"Plano, TX 75086",2024-10-06,"This role oversees pricing for complex, multi-...",NaN,https://www.indeed.com/m/viewjob?jk=7aec3d3abb...,IndeedScraperUSAEng_7aec3d3abb0b0309,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,UNKNOWN,TX 75086,TX,Plano,Senior-Level
341,NEW,data scientist (new york),The Voleon Group,"New York, NY",2024-10-09,Design and implement systems to ensure data co...,Job types: Full-time\r\nRemote: Hybrid work\r\...,https://www.indeed.com/m/viewjob?jk=737db02d03...,IndeedScraperUSAEng_737db02d039f691b,IndeedScraperUSAEng,Data,USA_ENGLISH,$150000 - $190000 yearly,TEMPORARILY_REMOTE,NY,NY,New York,Mid-Level
342,NEW,statistician,Outlier,"Raleigh, NC",2024-11-05,Outlier is looking for talented Math Experts t...,"Job types: Contract\r\nJob types cc: Contract,...",https://www.indeed.com/m/viewjob?jk=f28836fcac...,IndeedScraperUSAEng_f28836fcac3347e3,IndeedScraperUSAEng,Data,USA_ENGLISH,$30 - $50 hourly,UNKNOWN,NC,NC,Raleigh,Uncategorized
343,NEW,enterprise integration and data architect,KPMG,"Raleigh, NC",2024-11-01,Facilitate meaningful organizational change by...,Remote: Remote\r\nBenefits: Disability insuran...,https://www.indeed.com/m/viewjob?jk=75d145417c...,IndeedScraperUSAEng_75d145417c1d8e1c,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,FULLY_REMOTE,NC,NC,Raleigh,Senior-Level

In [19]:
labeled['job_level'].value_counts()

job_level
Uncategorized    152
Mid-Level        103
Senior-Level      46
Entry-Level       43
Name: count, dtype: int64