#### Combine All days together

In [1]:
import pandas as pd

##### SF

In [2]:
#read in all SF files
sf_2 = pd.read_csv('11_2_pull/SF_Jobs.csv') #960
sf_4 = pd.read_csv('Data_until11_4/USA_Jobs.csv') #1544
sf_5 = pd.read_csv('11_5/USA_Jobs.csv') #952
sf_6 = pd.read_csv('11_6/USA_Jobs.csv') #987
sf_7 = pd.read_csv('11_7/USA_Jobs.csv') #961
sf_8 = pd.read_csv('11_8/USA_Jobs.csv') #969
sf_9 = pd.read_csv('11_9/USA_Jobs.csv') #972
sf_10 = pd.read_csv('11_10/USA_Jobs.csv') #976
sf_11_12 = pd.read_csv('11_11_12/USA_Jobs.csv') #976
sf_13 = pd.read_csv('11_13/USA_Jobs.csv') #976
sf_14 = pd.read_csv('11_14/USA_Jobs.csv') #976
sf_15 = pd.read_csv('11_15/USA_Jobs.csv') #976
sf_16 = pd.read_csv('11_16/USA_Jobs.csv') #976
sf_17 = pd.read_csv('11_17/USA_Jobs.csv') #976

In [3]:
#stack df
sf = pd.concat([sf_2, sf_4, sf_5, sf_6, sf_7, sf_8, sf_9, sf_10, sf_11_12, sf_13, sf_14, sf_15, sf_16, sf_17], axis=0)

In [4]:
sf = sf.drop_duplicates(["id"])
#sf

In [5]:
sf['date'].value_counts()

date
2024-10-05    463
2024-10-03    373
2024-10-15    104
2024-10-10     90
2024-11-13     71
2024-10-08     66
2024-11-15     63
2024-11-05     63
2024-11-02     62
2024-11-07     60
2024-11-14     54
2024-10-22     52
2024-11-08     51
2024-11-09     51
2024-10-09     51
2024-11-01     51
2024-10-07     51
2024-10-26     50
2024-10-17     48
2024-10-18     46
2024-10-29     46
2024-10-30     46
2024-10-16     44
2024-10-24     44
2024-11-12     44
2024-10-31     42
2024-10-11     42
2024-11-06     41
2024-10-25     41
2024-10-23     35
2024-11-16     32
2024-10-12     30
2024-10-13     29
2024-10-19     26
2024-10-06     24
2024-10-14     21
2024-11-03     19
2024-11-11     16
2024-11-04     14
2024-10-04     10
2024-11-10      9
2024-10-21      9
2024-10-27      7
2024-10-28      5
2024-10-20      4
2024-11-17      4
Name: count, dtype: int64

##### NYC

In [6]:
#read in all SF files
nyc_2 = pd.read_csv('11_2_pull/NYC_Jobs.csv') #884
nyc_4 = pd.read_csv('Data_until11_4/NYC_Jobs.csv') #1002
nyc_5 = pd.read_csv('11_5/NYC_Jobs.csv') #902
nyc_6 = pd.read_csv('11_6/NYC_Jobs.csv') #885
nyc_7 = pd.read_csv('11_7/NYC_Jobs.csv') #885
nyc_8 = pd.read_csv('11_8/NYC_Jobs.csv') #933
nyc_9 = pd.read_csv('11_9/NYC_Jobs.csv') #942
nyc_10 = pd.read_csv('11_10/NYC_Jobs.csv') #901
nyc_11_12 = pd.read_csv('11_11_12/NYC_Jobs.csv') #901
nyc_13 = pd.read_csv('11_13/NYC_Jobs.csv') #901
nyc_14 = pd.read_csv('11_14/NYC_Jobs.csv') #901
nyc_15 = pd.read_csv('11_15/NYC_Jobs.csv') #901
nyc_16 = pd.read_csv('11_16/NYC_Jobs.csv') #901
nyc_17 = pd.read_csv('11_17/NYC_Jobs.csv') #901

#stack df
nyc = pd.concat([nyc_2, nyc_4, nyc_5, nyc_6, nyc_7, nyc_8, nyc_9, nyc_10, nyc_11_12, nyc_13, nyc_14, nyc_15, nyc_16, nyc_17], axis=0)
nyc = nyc.drop_duplicates(["id"])
#nyc

In [7]:
nyc['date'].value_counts()

date
2024-10-09    432
2024-10-03    339
2024-11-15    108
2024-11-07     90
2024-11-14     84
2024-11-08     81
2024-11-06     80
2024-11-05     77
2024-10-29     72
2024-11-01     66
2024-11-09     64
2024-10-16     59
2024-10-31     56
2024-10-30     56
2024-11-13     55
2024-11-02     53
2024-11-12     51
2024-10-23     51
2024-10-22     48
2024-10-08     48
2024-10-24     48
2024-10-05     47
2024-10-17     45
2024-10-13     44
2024-10-26     41
2024-10-10     40
2024-10-11     40
2024-11-16     37
2024-10-18     36
2024-10-25     36
2024-10-15     33
2024-11-04     32
2024-10-19     22
2024-10-12     17
2024-10-14     16
2024-10-07     14
2024-10-28     13
2024-11-10     13
2024-10-06     12
2024-10-21     12
2024-11-17      8
2024-11-11      7
2024-10-04      6
2024-10-20      2
2024-10-27      2
Name: count, dtype: int64

#### TX

In [8]:
#read in all SF files
tx_2 = pd.read_csv('11_2_pull/TX_Jobs.csv') #789
tx_4 = pd.read_csv('Data_until11_4/TX_Jobs.csv') #1293
tx_5 = pd.read_csv('11_5/TX_Jobs.csv') #790
tx_6 = pd.read_csv('11_6/TX_Jobs.csv') #935
tx_7 = pd.read_csv('11_7/TX_Jobs.csv') #935
tx_8 = pd.read_csv('11_8/TX_Jobs.csv') #935
tx_9 = pd.read_csv('11_9/TX_Jobs.csv') #935
tx_10 = pd.read_csv('11_10/TX_Jobs.csv') #935
tx_11_12 = pd.read_csv('11_11_12/TX_Jobs.csv') #935
tx_13 = pd.read_csv('11_13/TX_Jobs.csv') #935
tx_14 = pd.read_csv('11_14/TX_Jobs.csv') #935
tx_15 = pd.read_csv('11_15/TX_Jobs.csv') #935
tx_16 = pd.read_csv('11_16/TX_Jobs.csv') #935
tx_17 = pd.read_csv('11_17/TX_Jobs.csv') #935

#stack df
tx = pd.concat([tx_2, tx_4, tx_5, tx_6, tx_7, tx_8, tx_9, tx_10, tx_11_12, tx_13, tx_14, tx_15, tx_16, tx_17], axis=0)

tx = tx.drop_duplicates(["id"])
#tx

In [9]:
tx['date'].value_counts()

date
2024-10-05    363
2024-10-03    300
2024-11-05     78
2024-10-18     72
2024-11-07     64
2024-11-14     56
2024-11-01     56
2024-11-13     56
2024-11-08     53
2024-10-07     51
2024-11-15     51
2024-10-16     51
2024-11-12     48
2024-10-29     47
2024-10-22     47
2024-10-08     44
2024-10-25     44
2024-11-06     44
2024-11-02     43
2024-10-23     42
2024-10-31     42
2024-10-30     41
2024-11-09     41
2024-10-09     39
2024-10-17     37
2024-10-10     33
2024-10-06     30
2024-10-24     29
2024-10-15     26
2024-11-16     26
2024-10-19     26
2024-10-11     24
2024-10-12     24
2024-10-26     20
2024-11-11     19
2024-10-04     17
2024-11-04     16
2024-10-27     15
2024-11-10     11
2024-10-14      9
2024-10-13      8
2024-11-03      4
2024-10-20      4
2024-10-21      4
2024-10-28      4
2024-11-17      2
Name: count, dtype: int64

##### NC

In [10]:
#read in all SF files
nc_2 = pd.read_csv('11_2_pull/NC_Jobs.csv') #789
nc_4 = pd.read_csv('Data_until11_4/NC_Jobs.csv') #1293
nc_5 = pd.read_csv('11_5/NC_Jobs.csv') #790
nc_6 = pd.read_csv('11_6/NC_Jobs.csv') #935
nc_7 = pd.read_csv('11_7/NC_Jobs.csv') #935
nc_8 = pd.read_csv('11_8/NC_Jobs.csv') #935
nc_9 = pd.read_csv('11_9/NC_Jobs.csv') #935
nc_10 = pd.read_csv('11_10/NC_Jobs.csv') #935
nc_11_12 = pd.read_csv('11_11_12/NC_Jobs.csv') #935
nc_13 = pd.read_csv('11_13/NC_Jobs.csv') #935
nc_14 = pd.read_csv('11_14/NC_Jobs.csv') #935
nc_15 = pd.read_csv('11_15/NC_Jobs.csv') #935
nc_16 = pd.read_csv('11_16/NC_Jobs.csv') #935
nc_17 = pd.read_csv('11_17/NC_Jobs.csv') #935

#stack df
nc = pd.concat([nc_2, nc_4, nc_5, nc_6, nc_7, nc_8, nc_9, nc_10, nc_11_12, nc_13, nc_14, nc_15, nc_16, nc_17], axis=0)

nc = nc.drop_duplicates(["id"])
#nc

In [11]:
nc['date'].value_counts()

date
2024-10-09    270
2024-11-05     75
2024-10-03     70
2024-10-11     29
2024-11-04     28
2024-11-02     26
2024-10-17     24
2024-11-15     23
2024-10-25     22
2024-11-01     22
2024-11-13     22
2024-10-16     20
2024-11-14     20
2024-11-10     20
2024-10-29     20
2024-10-31     19
2024-10-26     18
2024-10-15     18
2024-11-07     18
2024-11-09     17
2024-11-12     17
2024-10-05     16
2024-10-13     15
2024-11-08     15
2024-10-30     15
2024-10-24     15
2024-10-18     15
2024-10-23     13
2024-10-22     12
2024-10-06     11
2024-11-16     10
2024-10-10      9
2024-11-06      9
2024-10-12      7
2024-10-28      7
2024-10-14      7
2024-10-07      7
2024-10-08      6
2024-10-19      6
2024-11-17      4
2024-10-21      4
2024-11-11      1
2024-10-27      1
2024-10-20      1
2024-10-04      1
Name: count, dtype: int64

##### Combine all places & export

In [12]:
all_jobs = pd.concat([sf, nyc, tx, nc], axis=0)
all_jobs

,status,title,company,location,date,blurb,tags,link,id,provider,query,locale,wage,remoteness
0,NEW,Direct Data Entry Operator,WESTAMERICA BANK,"Fairfield, CA 94534",2024-10-17,"As a Direct Data Entry Operator, under general...",Job types: Full-time\r\nJob types cc: Full-time,https://www.indeed.com/m/viewjob?jk=9af5925791...,IndeedScraperUSAEng_9af5925791536fd2,IndeedScraperUSAEng,Data,USA_ENGLISH,$16 - $17.07 hourly,UNKNOWN
1,NEW,Cloud Data Architect-Director,CEDENT,"San Francisco, CA",2024-10-03,"Provide data engineers, quant engineers and re...",Job types: Full-time\r\nJob types cc: Full-time,https://www.indeed.com/m/viewjob?jk=66827a8f8e...,IndeedScraperUSAEng_66827a8f8e70c0e9,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,UNKNOWN
2,NEW,Data Aide 2,Stanford University,"Stanford, CA",2024-10-03,Develop and apply novel clinical data curation...,Job types: Full-time\r\nJob types cc: Full-time,https://www.indeed.com/m/viewjob?jk=db7d847fbf...,IndeedScraperUSAEng_db7d847fbf8a9612,IndeedScraperUSAEng,Data,USA_ENGLISH,$31.21 - $35.6 hourly,UNKNOWN
3,NEW,Field Applications Engineer - Data Center,Amphenol TCS,"Santa Clara, CA",2024-10-22,Amphenol High Speed and Commercial Products Gr...,"Benefits: Paid holidays, Disability insurance,...",https://www.indeed.com/m/viewjob?jk=cfb3f4f072...,IndeedScraperUSAEng_cfb3f4f072371529,IndeedScraperUSAEng,Data,USA_ENGLISH,$80750 - $148870 yearly,UNKNOWN
4,NEW,"Analyst, YouthTruth",CEP Global,"San Francisco, CA",2024-10-03,"Over time, contribute insights to new features...","Benefits: Dental insurance, 401(k), Flexible s...",https://www.indeed.com/m/viewjob?jk=9365df687b...,IndeedScraperUSAEng_9365df687b5694e9,IndeedScraperUSAEng,Data,USA_ENGLISH,$90756 - $90756 yearly,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,NEW,"Lead Business Analyst - Cell, Gene and Advance...",McKesson,"Cary, NC 27513",2024-11-17,"McKesson is an impact-driven, Fortune 10 compa...",NaN,https://www.indeed.com/m/viewjob?jk=e036e76d56...,IndeedScraperUSAEng_e036e76d56e391e3,IndeedScraperUSAEng,Data,USA_ENGLISH,$114000 - $190000 yearly,UNKNOWN
185,NEW,"Senior Staff Software Engineer, Storage AI/ML ...",Google,"Durham, NC",2024-11-16,"8 years of experience in software development,...",Job types: Full-time\r\nJob types cc: Full-time,https://www.indeed.com/m/viewjob?jk=6e36014f8e...,IndeedScraperUSAEng_6e36014f8e2f06eb,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,UNKNOWN
198,NEW,Project Manager - Data Center Construction ($8...,Miller Electric Company,"Winston-Salem, NC 27101",2024-10-21,"In this role, you will lead a team to manage t...",Job types: Full-time\r\nBenefits: Profit shari...,https://www.indeed.com/m/viewjob?jk=856953a651...,IndeedScraperUSAEng_856953a651b39778,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,UNKNOWN
205,NEW,Data Scientist II,Carpenter Technology,"Raleigh, NC",2024-11-17,Carpenter Technology Corporation is a leading ...,Job types: Full-time\r\nBenefits: Disability i...,https://www.indeed.com/m/viewjob?jk=81c010160c...,IndeedScraperUSAEng_81c010160c9c18c4,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,UNKNOWN
225,NEW,DATA MANAGER I-STUDENT INFO,Guilford County Schools,"Greensboro, NC 27455",2024-11-17,Fair Labor Standards Act Classification: Non-E...,Job types: Full-time\r\nJob types cc: Full-time,https://www.indeed.com/m/viewjob?jk=059d11ab07...,IndeedScraperUSAEng_059d11ab076611ab,IndeedScraperUSAEng,Data,USA_ENGLISH,$16.23 - $16.23 hourly,UNKNOWN

In [13]:
all_jobs.to_csv("all_jobs.csv", index=False)

#### Clean up City & State Columns

In [14]:
all_jobs = pd.read_csv('all_jobs.csv')
all_jobs_cleaned = all_jobs.copy()

In [15]:
all_jobs_cleaned #8363

,status,title,company,location,date,blurb,tags,link,id,provider,query,locale,wage,remoteness
0,NEW,Direct Data Entry Operator,WESTAMERICA BANK,"Fairfield, CA 94534",2024-10-17,"As a Direct Data Entry Operator, under general...",Job types: Full-time\r\nJob types cc: Full-time,https://www.indeed.com/m/viewjob?jk=9af5925791...,IndeedScraperUSAEng_9af5925791536fd2,IndeedScraperUSAEng,Data,USA_ENGLISH,$16 - $17.07 hourly,UNKNOWN
1,NEW,Cloud Data Architect-Director,CEDENT,"San Francisco, CA",2024-10-03,"Provide data engineers, quant engineers and re...",Job types: Full-time\r\nJob types cc: Full-time,https://www.indeed.com/m/viewjob?jk=66827a8f8e...,IndeedScraperUSAEng_66827a8f8e70c0e9,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,UNKNOWN
2,NEW,Data Aide 2,Stanford University,"Stanford, CA",2024-10-03,Develop and apply novel clinical data curation...,Job types: Full-time\r\nJob types cc: Full-time,https://www.indeed.com/m/viewjob?jk=db7d847fbf...,IndeedScraperUSAEng_db7d847fbf8a9612,IndeedScraperUSAEng,Data,USA_ENGLISH,$31.21 - $35.6 hourly,UNKNOWN
3,NEW,Field Applications Engineer - Data Center,Amphenol TCS,"Santa Clara, CA",2024-10-22,Amphenol High Speed and Commercial Products Gr...,"Benefits: Paid holidays, Disability insurance,...",https://www.indeed.com/m/viewjob?jk=cfb3f4f072...,IndeedScraperUSAEng_cfb3f4f072371529,IndeedScraperUSAEng,Data,USA_ENGLISH,$80750 - $148870 yearly,UNKNOWN
4,NEW,"Analyst, YouthTruth",CEP Global,"San Francisco, CA",2024-10-03,"Over time, contribute insights to new features...","Benefits: Dental insurance, 401(k), Flexible s...",https://www.indeed.com/m/viewjob?jk=9365df687b...,IndeedScraperUSAEng_9365df687b5694e9,IndeedScraperUSAEng,Data,USA_ENGLISH,$90756 - $90756 yearly,UNKNOWN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8358,NEW,"Lead Business Analyst - Cell, Gene and Advance...",McKesson,"Cary, NC 27513",2024-11-17,"McKesson is an impact-driven, Fortune 10 compa...",NaN,https://www.indeed.com/m/viewjob?jk=e036e76d56...,IndeedScraperUSAEng_e036e76d56e391e3,IndeedScraperUSAEng,Data,USA_ENGLISH,$114000 - $190000 yearly,UNKNOWN
8359,NEW,"Senior Staff Software Engineer, Storage AI/ML ...",Google,"Durham, NC",2024-11-16,"8 years of experience in software development,...",Job types: Full-time\r\nJob types cc: Full-time,https://www.indeed.com/m/viewjob?jk=6e36014f8e...,IndeedScraperUSAEng_6e36014f8e2f06eb,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,UNKNOWN
8360,NEW,Project Manager - Data Center Construction ($8...,Miller Electric Company,"Winston-Salem, NC 27101",2024-10-21,"In this role, you will lead a team to manage t...",Job types: Full-time\r\nBenefits: Profit shari...,https://www.indeed.com/m/viewjob?jk=856953a651...,IndeedScraperUSAEng_856953a651b39778,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,UNKNOWN
8361,NEW,Data Scientist II,Carpenter Technology,"Raleigh, NC",2024-11-17,Carpenter Technology Corporation is a leading ...,Job types: Full-time\r\nBenefits: Disability i...,https://www.indeed.com/m/viewjob?jk=81c010160c...,IndeedScraperUSAEng_81c010160c9c18c4,IndeedScraperUSAEng,Data,USA_ENGLISH,NaN,UNKNOWN
8362,NEW,DATA MANAGER I-STUDENT INFO,Guilford County Schools,"Greensboro, NC 27455",2024-11-17,Fair Labor Standards Act Classification: Non-E...,Job types: Full-time\r\nJob types cc: Full-time,https://www.indeed.com/m/viewjob?jk=059d11ab07...,IndeedScraperUSAEng_059d11ab076611ab,IndeedScraperUSAEng,Data,USA_ENGLISH,$16.23 - $16.23 hourly,UNKNOWN

In [16]:
#create state column
all_jobs_cleaned['state_zip'] = all_jobs['location'].str.split(',').str[1]
all_jobs_cleaned['state'] = all_jobs_cleaned['state_zip'].str.split(' ').str[1]
# #create city column
all_jobs_cleaned['city'] = all_jobs_cleaned['location'].str.split(',').str[0]
#all_jobs_cleaned

In [17]:
all_jobs_cleaned.to_csv("all_jobs_cleaned.csv", index=False)

##### Export out df of individual states

In [20]:
ca = all_jobs_cleaned.loc[all_jobs_cleaned['state'] == 'CA']
ca.to_csv("ca.csv", index=False)

# ny = all_jobs_cleaned.loc[all_jobs_cleaned['state'] == 'NY']
# ny.to_csv("ny.csv", index=False)

# tx = all_jobs_cleaned.loc[all_jobs_cleaned['state'] == 'TX']
# tx.to_csv("tx.csv", index=False)

# nc = all_jobs_cleaned.loc[all_jobs_cleaned['state'] == 'NC']
# nc.to_csv("nc.csv", index=False)

#### Pool Neighborhoods into Cities

In [19]:
for index, row in all_jobs_cleaned.iterrows():
    if all_jobs_cleaned['state'][index] == 'CA':
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('San Francisco'), 'city'] = 'San Francisco'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('East Bay'), 'city'] = 'Oakland'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('SF County'), 'city'] = 'San Francisco'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Stanford'), 'city'] = 'Palo Alto'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Santa Clara County'), 'city'] = 'Santa Clara'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Sacramento'), 'city'] = 'Sacramento'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('East Palo Alto'), 'city'] = 'Palo Alto'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Travis AFB'), 'city'] = 'Fairfield'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('San Joaquin'), 'city'] = 'Ripon'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('San Mateo County'), 'city'] = 'San Mateo'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Oakland-Berkeley'), 'city'] = 'Oakland'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Silicon Valley'), 'city'] = 'San Jose'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Peninsula'), 'city'] = 'San Mateo'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('August'), 'city'] = 'Stockton'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('El Dorado Hills'), 'city'] = 'Folsom'

    if all_jobs_cleaned['state'][index] == 'TX':
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Dallas County'), 'city'] = 'Dallas'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Tarrant county'), 'city'] = 'Fort Worth'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Las Colinas'), 'city'] = 'Irving'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Addison'), 'city'] = 'Dallas'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Dallas-Fort Worth'), 'city'] = 'Fort Worth'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('The Colony'), 'city'] = 'Frisco'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Westlake'), 'city'] = 'Fort Worth'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Burleson'), 'city'] = 'Fort Worth'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Allen'), 'city'] = 'Dallas '

    if all_jobs_cleaned['state'][index] == 'NY':
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('New york'), 'city'] = 'Manhattan' 
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Woodside'), 'city'] = 'Queens'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('College Point'), 'city'] = 'Queens'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Richmond Hill'), 'city'] = 'Queens'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Far Rockaway'), 'city'] = 'Queens'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Williamsburg'), 'city'] = 'Brooklyn'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Greenpoint'), 'city'] = 'Brooklyn'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Bushwick'), 'city'] = 'Brooklyn'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Riverdale'), 'city'] = 'Bronx'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Richmond'), 'city'] = 'Staten Island'

    if all_jobs_cleaned['state'][index] == 'NC':
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Research Triangle Park'), 'city'] = 'Raleigh'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Raleigh-Durham'), 'city'] = 'Raleigh'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Fort Liberty'), 'city'] = 'Fayetteville'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Wake County'), 'city'] = 'Raleigh'
        all_jobs_cleaned.loc[all_jobs_cleaned['city'].str.contains('Browns Summit'), 'city'] = 'Greensboro'

In [75]:
ca = all_jobs_cleaned.loc[all_jobs_cleaned['state'] == 'CA']
ca.to_csv("ca.csv", index=False)

ny = all_jobs_cleaned.loc[all_jobs_cleaned['state'] == 'NY']
ny.to_csv("ny.csv", index=False)

tx = all_jobs_cleaned.loc[all_jobs_cleaned['state'] == 'TX']
tx.to_csv("tx.csv", index=False)

nc = all_jobs_cleaned.loc[all_jobs_cleaned['state'] == 'NC']
nc.to_csv("nc.csv", index=False)

In [ ]:
# import requests
# from bs4 import BeautifulSoup

In [ ]:
# # Fetch the HTML content from the website
# url = "https://www.example.com"
# response = requests.get(url)
# html_content = response.content

In [ ]:

# # Parse the HTML using BeautifulSoup
# soup = BeautifulSoup(html_content, 'html.parser')

# # Extract all links from the page
# links = soup.find_all('a')

# # Print the href attribute of each link
# for link in links:
#     href = link.get('href')
#     if href:
#         print(href)

In [ ]:
#see which types of jobs are growing 
#segments of jobs 
#prefixspan
#5 key words are they a good prediction of the data 

#glove embedding